export const filterOptions = { 
   shapes: [ 
     "Round", 
     "Pear", 
     "Emerald", 
     "Oval", 
     "Heart", 
     "Marquise", 
     "Asscher", 
     "Cushion", 
     "Cushion modified", 
     "Cushion brilliant", 
     "Radiant", 
     "Princess", 
     "French", 
     "Trilliant", 
     "Euro cut", 
     "Old Miner", 
     "Briollette", 
     "Rose cut", 
     "Lozenge", 
     "Baguette", 
     "Tapered baguette", 
     "Half-moon", 
     "Flanders", 
     "Trapezoid", 
     "Bullet", 
     "Kite", 
     "Shield", 
     "Star cut", 
     "Pentagonal cut", 
     "Hexagonal cut", 
     "Octagonal cut", 
     "Portugeese cut", 
   ], 
   colors: [ 
     "D", 
     "E", 
     "F", 
     "G", 
     "H", 
     "I", 
     "J", 
     "K", 
     "L", 
     "M", 
     "N", 
     "O", 
     "P", 
     "Q", 
     "R", 
     "S", 
     "T", 
     "U", 
     "V", 
     "W", 
     "X", 
     "Y", 
     "Z", 
   ], 
   cutGrades: ["Ideal", "Excellent", "Very Good", "Good", "Fair", "Poor"], 
   clarities: ["IF", "VVS1", "VVS2", "VS1","VS2", "SI1", "SI2","SI3", "I1", "I2", "I3"],
  fluorescences: ["None", "Faint", "Medium", "Strong", "Very Strong"],
  symmetry: ["Ideal", "Excellent", "Very Good", "Good", "Fair", "Poor"],
  polish: ["Ideal", "Excellent", "Very Good", "Good", "Fair", "Poor"],
  finish: ["3X", "EX-", "VG+", "VG-"],
  certifications: ["GIA", "HRD", "IGI", "EGL", "AGS"],
  productType: ["Certified", "Non-certified"],
  diamondType: ["Natural", "CVD", "HPHT"],
  overTone:["Yellow","Yellowish", "pink","pinkish","blue","blueish","green","greenish","orange","orangy","brown","brownish","red","redish","violet","violetish","gray","grayish","black","blackish","white","whiteish","chameleon","champagne","cognac" , "Other"],
  intensity:["faint","very light", "light", "fancy light" ,"fancy", "fancy intense" ,"fancy vivid" , "fancy deep", "fancy dark"],
  gridleOptions :["extremely thin","very thin", "thin","slightly thin" ,"medium" ,"slightly thick" ,"thick" ,"very thick" ,"extremely thick"],
  culetSizeOptions :["none","very small","small","medium","slightly large","large","very large", "extremely large"],
  whiteColors: ["D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"],
  companies: [
    "De Beers",
    "Alrosa",
    "Rio Tinto",
    "Petra Diamonds",
    "Dominion Diamond Mines",
    "Lucara Diamond",
    "Gem Diamonds",
    "Stornoway Diamond",
    "Mountain Province Diamonds",
    "Other"
  ],
  locations: [
    "Antwerp",
    "Dubai",
    "Mumbai",
    "New York",
    "Tel Aviv",
    "Hong Kong",
    "Shanghai",
    "Singapore",
    "London",
    "Other"
  ]
};
