import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppProviders } from "../provider";
import ConditionalNavigation from "../components";
import { ThemeProvider } from "@/components/theme/ThemeProvider";
import dynamic from "next/dynamic";
import { BuyerThemeWrapper } from "@/components/theme/BuyerThemeWrapper";

const FloatingCompareBar = dynamic(
  () => import("@/components/compare/FloatingCompareBar")
);

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <BuyerThemeWrapper>
            <AppProviders>
              <FloatingCompareBar />
              {children}
            </AppProviders>
          </BuyerThemeWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
