import type { InquiryCategory } from './inquiryTypes'

/**
 * Field order and labels aligned with be-ohana Create*InquiryDto classes
 * (create-diamond-inquiry.dto.ts, create-gemstone-inquiry.dto.ts, etc.).
 */
export type InquiryDtoField = { key: string; label: string }

export const INQUIRY_DTO_FIELDS: Record<InquiryCategory, readonly InquiryDtoField[]> = {
  diamond: [
    { key: 'subCategory', label: 'Sub category (PARCEL / SINGLE)' },
    { key: 'diamondType', label: 'Diamond type (LAB / NATURAL)' },
    { key: 'growthProcess', label: 'Growth process (LAB only)' },
    { key: 'isCertified', label: 'Certified' },
    { key: 'certificateCompany', label: 'Certificate company' },
    { key: 'sieveSizeMin', label: 'Minimum sieve size (PARCEL)' },
    { key: 'sieveSizeMax', label: 'Maximum sieve size (PARCEL)' },
    { key: 'shape', label: 'Shape' },
    { key: 'caratMin', label: 'Minimum carat weight' },
    { key: 'caratMax', label: 'Maximum carat weight' },
    { key: 'colorMin', label: 'Minimum color grade' },
    { key: 'colorMax', label: 'Maximum color grade' },
    { key: 'clarityMin', label: 'Minimum clarity grade' },
    { key: 'clarityMax', label: 'Maximum clarity grade' },
    { key: 'cut', label: 'Cut quality' },
    { key: 'bgm', label: 'BGM (brown/green/milky)' },
    { key: 'inclusionType', label: 'Inclusion type' },
    { key: 'fluorescenceIntensityMin', label: 'Minimum fluorescence intensity' },
    { key: 'fluorescenceIntensityMax', label: 'Maximum fluorescence intensity' },
    { key: 'quantity', label: 'Quantity' },
    { key: 'totalPriceMin', label: 'Minimum total price' },
    { key: 'totalPriceMax', label: 'Maximum total price' },
    { key: 'pricePerCaratMin', label: 'Minimum price per carat' },
    { key: 'pricePerCaratMax', label: 'Maximum price per carat' },
    { key: 'paymentTerms', label: 'Payment terms' },
    { key: 'remarks', label: 'Remarks' },
    { key: 'lengthMin', label: 'Minimum length (SINGLE)' },
    { key: 'lengthMax', label: 'Maximum length' },
    { key: 'widthMin', label: 'Minimum width' },
    { key: 'widthMax', label: 'Maximum width' },
    { key: 'heightMin', label: 'Minimum height' },
    { key: 'heightMax', label: 'Maximum height' },
    { key: 'urgency', label: 'Urgency date' },
    { key: 'imageUrl', label: 'Reference image URL' },
    { key: 'deliveryLocation', label: 'Delivery location' },
  ],
  gemstone: [
    { key: 'isCertified', label: 'Certified' },
    { key: 'certificateCompany', label: 'Certificate company' },
    { key: 'gemstoneType', label: 'Gemstone type' },
    { key: 'shape', label: 'Shape' },
    { key: 'primaryColorMin', label: 'Primary color (min)' },
    { key: 'primaryColorMax', label: 'Primary color (max)' },
    { key: 'clarity', label: 'Clarity' },
    { key: 'caratWeightMin', label: 'Minimum carat weight' },
    { key: 'caratWeightMax', label: 'Maximum carat weight' },
    { key: 'origin', label: 'Origin' },
    { key: 'treatment', label: 'Treatment' },
    { key: 'quantity', label: 'Quantity' },
    { key: 'totalPriceMin', label: 'Minimum total price' },
    { key: 'totalPriceMax', label: 'Maximum total price' },
    { key: 'pricePerCaratMin', label: 'Minimum price per carat' },
    { key: 'pricePerCaratMax', label: 'Maximum price per carat' },
    { key: 'description', label: 'Description' },
    { key: 'paymentTerms', label: 'Payment terms' },
    { key: 'lengthMin', label: 'Minimum length' },
    { key: 'lengthMax', label: 'Maximum length' },
    { key: 'widthMin', label: 'Minimum width' },
    { key: 'widthMax', label: 'Maximum width' },
    { key: 'heightMin', label: 'Minimum height' },
    { key: 'heightMax', label: 'Maximum height' },
    { key: 'urgency', label: 'Urgency date' },
    { key: 'imageUrl', label: 'Reference image URL' },
    { key: 'deliveryLocation', label: 'Delivery location' },
  ],
  bullion: [
    { key: 'isCertified', label: 'Certified' },
    { key: 'certificateCompany', label: 'Certificate company' },
    { key: 'metalType', label: 'Metal type' },
    { key: 'metalFineness', label: 'Metal fineness' },
    { key: 'shapeFormat', label: 'Shape format (coin / bar / biscuit)' },
    { key: 'weightMin', label: 'Minimum weight' },
    { key: 'weightMax', label: 'Maximum weight' },
    { key: 'preferredMint', label: 'Preferred mint' },
    { key: 'quantity', label: 'Quantity' },
    { key: 'totalPriceMin', label: 'Minimum total price' },
    { key: 'totalPriceMax', label: 'Maximum total price' },
    { key: 'pricePerGramMin', label: 'Minimum price per gram' },
    { key: 'pricePerGramMax', label: 'Maximum price per gram' },
    { key: 'description', label: 'Description' },
    { key: 'paymentTerms', label: 'Payment terms' },
    { key: 'lengthMin', label: 'Minimum length' },
    { key: 'lengthMax', label: 'Maximum length' },
    { key: 'widthMin', label: 'Minimum width' },
    { key: 'widthMax', label: 'Maximum width' },
    { key: 'heightMin', label: 'Minimum height' },
    { key: 'heightMax', label: 'Maximum height' },
    { key: 'urgency', label: 'Urgency date' },
    { key: 'imageUrl', label: 'Reference image URL' },
    { key: 'deliveryLocation', label: 'Delivery location' },
  ],
  watch: [
    { key: 'brand', label: 'Brand' },
    { key: 'model', label: 'Model' },
    { key: 'referenceNumber', label: 'Reference number' },
    { key: 'yearMin', label: 'Minimum year' },
    { key: 'yearMax', label: 'Maximum year' },
    { key: 'totalPriceMin', label: 'Minimum total price' },
    { key: 'totalPriceMax', label: 'Maximum total price' },
    { key: 'caseMaterial', label: 'Case material' },
    { key: 'caseSizeMin', label: 'Minimum case size (mm)' },
    { key: 'caseSizeMax', label: 'Maximum case size (mm)' },
    { key: 'dialColor', label: 'Dial color' },
    { key: 'strapMaterial', label: 'Strap / bracelet material' },
    { key: 'movement', label: 'Movement' },
    { key: 'hasOriginalBox', label: 'Has original box' },
    { key: 'hasWarrantyPapers', label: 'Has warranty papers' },
    { key: 'hasManuals', label: 'Has manuals / tags' },
    { key: 'condition', label: 'Condition' },
    { key: 'description', label: 'Description' },
    { key: 'urgency', label: 'Urgency date' },
    { key: 'imageUrl', label: 'Reference image URL' },
    { key: 'deliveryLocation', label: 'Delivery location' },
  ],
  jewelry: [
    { key: 'subCategory', label: 'Sub category' },
    { key: 'occasion', label: 'Occasion' },
    { key: 'intendedWearer', label: 'Intended wearer' },
    { key: 'metalType', label: 'Metal type' },
    { key: 'metalColor', label: 'Metal color' },
    { key: 'metalPurity', label: 'Metal purity' },
    { key: 'finish', label: 'Finish' },
    { key: 'hasStone', label: 'Has stone' },
    { key: 'stoneType', label: 'Stone type (NATURAL / LAB)' },
    { key: 'stoneShape', label: 'Stone shape' },
    { key: 'stoneCaratMin', label: 'Minimum stone carat' },
    { key: 'stoneCaratMax', label: 'Maximum stone carat' },
    { key: 'stoneColorMin', label: 'Minimum stone color' },
    { key: 'stoneColorMax', label: 'Maximum stone color' },
    { key: 'stoneClarityMin', label: 'Minimum stone clarity' },
    { key: 'stoneClarityMax', label: 'Maximum stone clarity' },
    { key: 'stoneCut', label: 'Stone cut' },
    { key: 'stoneQuantity', label: 'Stone quantity' },
    { key: 'settingType', label: 'Setting type' },
    { key: 'ringSize', label: 'Ring size' },
    { key: 'chainLengthMin', label: 'Minimum chain length' },
    { key: 'chainLengthMax', label: 'Maximum chain length' },
    { key: 'widthMin', label: 'Minimum width' },
    { key: 'widthMax', label: 'Maximum width' },
    { key: 'thicknessMin', label: 'Minimum thickness' },
    { key: 'thicknessMax', label: 'Maximum thickness' },
    { key: 'approxWeightMin', label: 'Minimum approximate weight' },
    { key: 'approxWeightMax', label: 'Maximum approximate weight' },
    { key: 'isEngravingRequired', label: 'Engraving required' },
    { key: 'engravingText', label: 'Engraving text' },
    { key: 'quantity', label: 'Quantity' },
    { key: 'totalPriceMin', label: 'Minimum total price' },
    { key: 'totalPriceMax', label: 'Maximum total price' },
    { key: 'paymentTerms', label: 'Payment terms' },
    { key: 'designDescription', label: 'Design description' },
    { key: 'referenceImage', label: 'Reference image URL' },
    { key: 'referenceVideo', label: 'Reference video URL' },
    { key: 'urgency', label: 'Urgency date' },
    { key: 'deliveryLocation', label: 'Delivery location' },
  ],
}

/** Stored on the record but not part of POST body — shown after DTO section. */
export const INQUIRY_METADATA_FIELDS: readonly InquiryDtoField[] = [
  { key: 'id', label: 'Inquiry ID' },
  { key: 'userId', label: 'User ID' },
  { key: 'createdAt', label: 'Created at' },
  { key: 'updatedAt', label: 'Updated at' },
]
